#ifndef TALLERZ_CLIENTE_BUILDINGEFFECTTYPE_H
#define TALLERZ_CLIENTE_BUILDINGEFFECTTYPE_H

enum BuildingEffectType {SPIN, PRODUCT, SMOKE, GREEN_BOX, VENT, BULB};

#endif //TALLERZ_CLIENTE_BUILDINGEFFECTTYPE_H
