#ifndef TALLERZ_EFFECTTYPE_H
#define TALLERZ_EFFECTTYPE_H

enum EffectType {TANK_MISSILE, SIDE_EXPLOSION,BIG_SMOKE, FIRE_SMOKE,
                 FIRE_EFFECT, FIRE2_EFFECT, LASER_EFFECT};

#endif //TALLERZ_EFFECTTYPE_H
