//
// Created by darius on 01/06/17.
//

#ifndef TALLERZ_GENERADOR_MAPTYPE_H
#define TALLERZ_GENERADOR_MAPTYPE_H

enum MAP_TYPE { WINTER, SPRING, HUMID, DUSTY, HELL};

#endif //TALLERZ_GENERADOR_MAPTYPE_H
